### ISSUE TITLE
Permission denied while user seted

### ISSUE THREAD

**Issue by honwen** [pymumu/tinylog#9]
daemon.err smartdns[32515]: gzip: can't open '/var/log/smartdns.log.pending.gz': Permission denied

**Comment by honwen** [comment]
related code: https://github.com/pymumu/tinylog/blob/6250ec1191ba925412c2e31d6b4a163ce63895ba/tlog.c#L1035

**Comment by honwen** [comment]
related change: https://github.com/pymumu/smartdns/commit/362b7f978f3fe0a190f94566c7cd48b273739632

with config:
`config
user dnsmasq
`

**Comment by pymumu** [comment]
The smartdns log by default is written to /var/log which the owner of the directory is root, after dropping root permission, the log cannot be written any more.

The temporary solution is to manually create a directory like `/var/log/smartdns` with `dnsmasq` user permission, and then set the log file path of smartdns to `/var/log/smartdns/smartdns.log`

The next version will create this directory while installation, and then the feature can be fully opened.

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/commit/d3bbd8edd7c589e45ace9d597daf3d977df7685b

please try

**Comment by honwen** [comment]
log with gzip works now
